export const Galleries = [
  {
    galleryId: '1',
    title: 'Bułgaria',
    dateCreated: '2015-12-15T00:00:00+00:00',
    thumbUrl: 'gallery/assets/img/bulgaria.jpg',
    description: 'Kilka dni zwariowanego wypadu do bułgarii.',
    tags: [],
    photos: [],
  },
  {
    galleryId: '2',
    title: 'Koteże',
    dateCreated: '2022-09-07T00:00:00+00:00',
    thumbUrl: 'gallery/assets/img/koteze.jpg',
    description: 'koteze z dawidem',
    tags: [],
    photos: [],
  },
  {
    galleryId: '3',
    title: 'Niemcy',
    dateCreated: '2013-07-10T00:00:00+00:00',
    thumbUrl: 'gallery/assets/img/niemcy.jpg',
    description: 'z dawidem w niemcach',
    tags: [],
    photos: [],
  },
  {
    galleryId: '4',
    title: 'Sucumin',
    dateCreated: '2015-12-10T00:00:00+00:00',
    thumbUrl: 'gallery/assets/img/sucumin.jpg',
    description: 'lepszy sumin',
    tags: [],
    photos: [],
  },
  {
    galleryId: '5',
    title: 'Sumin',
    dateCreated: '2024-09-10T00:00:00+00:00',
    thumbUrl: 'gallery/assets/img/sumin.jpg',
    description: 'gorszy sucumin',
    tags: [],
    photos: [],
  },
  {
    galleryId: '6',
    title: 'Tajlandia',
    dateCreated: '2023-07-10T00:00:00+00:00',
    thumbUrl: 'gallery/assets/img/tajlandia.jpg',
    description: 'dawid mieszka w tajlandii',
    tags: [],
    photos: [],
  },
];
